#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: vbox
    username: vandoir
    password: "$6$LMe/g3WMDrPmF7ot$iUPiuNqSg/lBTagAzXpZG.upUJyckHHSF7eQvkeUpbYw7dgJYf/yiphV8U8bB19h9FhuFPksND.vvzcmKz/yo/"   # use mkpasswd -m sha-512 1234
  locale: pt_BR.UTF-8
  keyboard:
    layout: br
  storage:
    layout:
      name: lvm
  packages:
    - linux-lowlatency
    - pipewire
    - pipewire-audio-client-libraries
    - pipewire-jack
    - wireplumber
    - pavucontrol
    - libsndfile1-dev
    - libcairo2-dev
    - libx11-dev
    - lv2-dev
  user-data:
    disable_root: false
  late-commands:
    # Cria a pasta do usuário para LV2
    - curtin in-target --target=/target -- mkdir -p /home/vandoir/.lv2

    # Baixa os pacotes do Ratatouille do GitHub
    - curtin in-target --target=/target -- bash -c "wget -qO /tmp/ratatouille.lv2.tar.xz https://github.com/brummer10/Ratatouille.lv2/releases/latest/download/Ratatouille.lv2-v0.9.11-linux-x86_64.tar.xz"
    - curtin in-target --target=/target -- bash -c "wget -qO /tmp/ratatouille.app.tar.xz https://github.com/brummer10/Ratatouille.lv2/releases/latest/download/Ratatouille.lv2-app-v0.9.11-linux-x86_64.tar.xz"

    # Extrai para os diretórios corretos
    - curtin in-target --target=/target -- tar -xJf /tmp/ratatouille.lv2.tar.xz -C /home/vandoir/.lv2
    - curtin in-target --target=/target -- mkdir -p /opt
    - curtin in-target --target=/target -- tar -xJf /tmp/ratatouille.app.tar.xz -C /opt

    # Ajusta permissões
    - curtin in-target --target=/target -- chown -R vandoir:vandoir /home/vandoir/.lv2

    # Cria o arquivo desktop
    - curtin in-target --target=/target -- bash -c "cat >/usr/share/applications/ratatouille.desktop <<'EOF'
[Desktop Entry]
Version=1.0
Name=Ratatouille
Comment=LV2 Audio Plugin Host
Exec=/opt/Ratatouille*/Ratatouille*
Icon=audio-card
Terminal=false
Type=Application
Categories=AudioVideo;Audio;X-Jack;X-LV2;
EOF"
