#cloud-config
autoinstall:
  version: 1
  updates: all
  shutdown: reboot
  drivers:
    install: true
  codecs:
    install: true
  identity:
    realname: "Vandoir Gerhard"
    hostname: vbox
    username: vandoir
    password: "$6$LMe/g3WMDrPmF7ot$iUPiuNqSg/lBTagAzXpZG.upUJyckHHSF7eQvkeUpbYw7dgJYf/yiphV8U8bB19h9FhuFPksND.vvzcmKz/yo/" # use mkpasswd -m sha-512 1234
  locale: pt_BR.UTF-8
  timezone: "America/Sao_Paulo"
  keyboard:
    layout: "br"
    variant: "abnt2"
    toggle: null
  storage:
    layout:
      name: lvm
  packages:
    - curl
    - linux-lowlatency
    - pipewire
    - pipewire-audio-client-libraries
    - pipewire-jack
    - wireplumber
    - pavucontrol
    - libsndfile1-dev
    - libcairo2-dev
    - libx11-dev
    - lv2-dev
    - flatpak
    - ibus
    - ibus-gtk
    - ibus-gtk3
    - language-pack-pt
    - language-pack-pt-base
    - language-pack-gnome-pt
    - language-pack-gnome-pt-base
    - gnome-software-plugin-flatpak
  late-commands:
    # Instala Ratatuille.vl2 para NAM (Neural Amp Modeler)
    - curtin in-target --target=/target -- bash -c "curl -fsSL https://raw.githubusercontent.com/VndrGrhrd/Ubuntu-AutoInstall/refs/heads/main/setup-neural-amp-modeler.sh | bash"

    # instala e configura o docker
    - curtin in-target --target=/target -- bash -c "curl -fsSL https://get.docker.com/ | bash"
    # - curtin in-target --target=/target -- bash -c "getent group docker || groupadd docker; usermod -aG docker vandoir"

    # Instalar programas extras
    - curtin in-target --target=/target -- sh -c "flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"
    - curtin in-target --target=/target -- sh -c "flatpak install -y flathub com.google.Chrome"
    - curtin in-target --target=/target -- sh -c "flatpak install -y flathub com.brave.Browser"
    - curtin in-target --target=/target -- sh -c "flatpak install -y it.mijorus.gearlever"
    - curtin in-target --target=/target -- sh -c "flatpak install -y com.github.tchx84.Flatseal"
    - curtin in-target --target=/target -- sh -c "flatpak install -y rest.insomnia.Insomnia"
    - curtin in-target --target=/target -- sh -c "snap install code --classic"
