#cloud-config
autoinstall:
  version: 1
  updates: all # Instalar todas as atualizações já na instalação
  shutdown: poweroff # Desliga após finalizar instalação
  # Instalar drives de Terceiros
  drivers:
    install: true
  # Instalar Codex de Terceiros (mp3, mp4...)
  codecs:
    install: true
  # Indentificação básica do usuário para a instalação
  identity:
    realname: "Vandoir Gerhard"
    hostname: vbox
    username: vandoir
    password: "$6$LMe/g3WMDrPmF7ot$iUPiuNqSg/lBTagAzXpZG.upUJyckHHSF7eQvkeUpbYw7dgJYf/yiphV8U8bB19h9FhuFPksND.vvzcmKz/yo/" # use mkpasswd -m sha-512 1234

  # Informação completa do usuário
  users:
    name: vandoir
    realname: "Vandoir Gerhard"
    shell: /bin/bash
    primary_group: vandoir
    groups:
      [
        rpa,
        adm,
        cdrom,
        sudo,
        dip,
        plugdev,
        users,
        kvm,
        lpadmin,
        docker,
        libvirt,
      ]
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    passwd: "$6$LMe/g3WMDrPmF7ot$iUPiuNqSg/lBTagAzXpZG.upUJyckHHSF7eQvkeUpbYw7dgJYf/yiphV8U8bB19h9FhuFPksND.vvzcmKz/yo/"
  # Idioma da interface
  locale: pt_BR.UTF-8
  # Fuzo-Horario
  timezone: "America/Sao_Paulo"
  # Teclado do Usuário
  keyboard:
    layout: "br"
  # Configuração de armazenamento
  storage:
    layout:
      name: lvm
  # Pacotes extras para instalar
  packages:
    - curl
    - linux-lowlatency
    - pipewire
    - pipewire-audio-client-libraries
    - pipewire-jack
    - wireplumber
    - pavucontrol
    - libsndfile1-dev
    - libcairo2-dev
    - libx11-dev
    - lv2-dev
    - flatpak
    - ibus
    - ibus-gtk
    - ibus-gtk3
    - language-pack-pt
    - language-pack-pt-base
    - language-pack-gnome-pt
    - language-pack-gnome-pt-base
    - gnome-software-plugin-flatpak
    - qemu-kvm
    - libvirt-daemon-system
    - libvirt-clients
    - virtinst
    - bridge-utils
    - virt-manager
    - ovmf
    - cpu-checker
  # Comandos / Configurações extras para o usuário
  late-commands:
    # Instala Ratatuille.vl2 para NAM (Neural Amp Modeler)
    - curtin in-target --target=/target -- bash -c "curl -fsSL https://raw.githubusercontent.com/VndrGrhrd/Ubuntu-AutoInstall/refs/heads/main/setup-neural-amp-modeler.sh | bash"

    # instala e configura o docker
    - curtin in-target --target=/target -- bash -c "curl -fsSL https://get.docker.com/ | bash"
    # Configurações extras executadas no primeiro boot
  user-data:
    package_update: false
    package_upgrade: false
    runcmd:
      - [chown, -R, vandoir:vandoir, /home/vandoir]
      - [usermod, -aG, docker, vandoir]
      - sudo -u vandoir flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      - sudo -u vandoir flatpak install -y flathub com.google.Chrome
      - sudo -u vandoir flatpak install -y flathub com.brave.Browser
      - sudo -u vandoir flatpak install -y flathub org.onlyoffice.desktopeditors
      - sudo -u vandoir flatpak install -y flathub it.mijorus.gearlever
      - sudo -u vandoir flatpak install -y flathub com.github.tchx84.Flatseal
      - sudo -u vandoir flatpak install -y flathub rest.insomnia.Insomnia
      - sudo -u vandoir flatpak install -y flathub com.visualstudio.code
      - sudo -u vandoir flatpak install -y flathub com.sublimetext.three
