#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: vbox
    username: vandoir
    password: "$6$LMe/g3WMDrPmF7ot$iUPiuNqSg/lBTagAzXpZG.upUJyckHHSF7eQvkeUpbYw7dgJYf/yiphV8U8bB19h9FhuFPksND.vvzcmKz/yo/"   # use mkpasswd -m sha-512 1234
  locale: pt_BR.UTF-8
  keyboard:
    layout: br
  storage:
    layout:
      name: lvm
  packages:
    - linux-lowlatency
    - pipewire
    - pipewire-audio-client-libraries
    - pipewire-jack
    - wireplumber
    - pavucontrol
    - libsndfile1-dev
    - libcairo2-dev
    - libx11-dev
    - lv2-dev
  late-commands:
    # Cria a pasta para LV2
    - mkdir -p /target/home/vandoir/.lv2
    - chown vandoir:vandoir /target/home/vandoir/.lv2

    # Baixa os pacotes do Ratatouille
    - wget -O /target/tmp/ratatouille.lv2.tar.xz https://github.com/brummer10/Ratatouille.lv2/releases/latest/download/Ratatouille.lv2-vx.x.x-linux-x86_64.tar.xz
    - wget -O /target/tmp/ratatouille.app.tar.xz https://github.com/brummer10/Ratatouille.lv2/releases/latest/download/Ratatouille.lv2-app-vx.x.x-linux-x86_64.tar.xz

    # Extrai para os diretórios corretos
    - tar -xJf /target/tmp/ratatouille.lv2.tar.xz -C /target/home/vandoir/.lv2
    - mkdir -p /target/opt
    - tar -xJf /target/tmp/ratatouille.app.tar.xz -C /target/opt

    # Ajusta permissões
    - chown -R vandoir:vandoir /target/home/vandoir/.lv2

    # Cria o arquivo desktop
    - |
      cat >/target/usr/share/applications/ratatouille.desktop <<'EOF'
      [Desktop Entry]
      Version=1.0
      Name=Ratatouille
      Comment=LV2 Audio Plugin Host
      Exec=/opt/Ratatouille*/Ratatouille*
      Icon=audio-card
      Terminal=false
      Type=Application
      Categories=AudioVideo;Audio;X-Jack;X-LV2;
      EOF
