#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: vbox
    username: vandoir
    password: "$6$LMe/g3WMDrPmF7ot$iUPiuNqSg/lBTagAzXpZG.upUJyckHHSF7eQvkeUpbYw7dgJYf/yiphV8U8bB19h9FhuFPksND.vvzcmKz/yo/"   # use mkpasswd -m sha-512 1234
  locale: pt_BR.UTF-8
  keyboard:
    layout: br
  storage:
    layout:
      name: lvm
  packages:
    - linux-lowlatency
    - pipewire
    - pipewire-audio-client-libraries
    - pipewire-jack
    - wireplumber
    - pavucontrol
    - libsndfile1-dev
    - libcairo2-dev
    - libx11-dev
    - lv2-dev
  late-commands:
    # Instala Ratatuille.vl2 para NAM (Neural Amp Modeler)
    - curtin in-target --target=/target -- bash -c "curl -fsSL https://raw.githubusercontent.com/VndrGrhrd/Ubuntu-AutoInstall/refs/heads/main/setup-neural-amp-modeler.sh | bash"
    
    # instala o docker
    - curtin in-target --target=/target -- bash -c "curl -fsSL https://get.docker.com/ | bash"

    # configuração docker pos-instalação
    - curtin in-target --target=/target -- usermod -aG docker vandoir
