#cloud-config
autoinstall:
  version: 1 # Define a versão do esquema de autoinstalação utilizado.
  updates: all # Durante a instalação, aplicar todas as atualizações disponíveis do sistema.
  shutdown: poweroff # Após o término da instalação, desligar a máquina automaticamente.
  locale: pt_BR.UTF-8 # Define o idioma e formatação regional para Português do Brasil.
  timezone: "America/Sao_Paulo" # Fuso horário configurado para São Paulo.

  drivers:
    install: true # Instala drivers de terceiros automaticamente (útil para placas de vídeo, Wi-Fi, etc).

  codecs:
    install: true # Instala codecs de mídia de terceiros (para suporte a formatos como mp3, mp4, etc).

  keyboard: # Configuração do layout do teclado.
    layout: "br" # Teclado padrão ABNT2 (brasileiro).

  storage:
    layout:
      name: lvm # Utiliza LVM (Logical Volume Manager) para o particionamento automático do disco.

  identity: # Informações básicas de identidade do sistema e do usuário administrador.
    realname: "Vandoir Gerhard" # Nome completo do usuário principal.
    hostname: vbox # Nome do host da máquina.
    username: vandoir # Nome de usuário do sistema.
    password: "$6$LMe/g3WMDrPmF7ot$iUPiuNqSg/lBTagAzXpZG.upUJyckHHSF7eQvkeUpbYw7dgJYf/yiphV8U8bB19h9FhuFPksND.vvzcmKz/yo/" # Senha criptografada do usuário (gerada com `mkpasswd -m sha-512`).

  packages: # Lista de pacotes adicionais a serem instalados durante o processo de autoinstalação.
    - curl # Utilitário para transferências HTTP.
    - flatpak # Sistema de pacotes universais.
    - qemu-kvm # Virtualização via KVM.
    - libvirt-daemon-system
    - libvirt-clients
    - virtinst
    - bridge-utils
    - virt-manager # Interface gráfica para gerenciar VMs.
    - ovmf # Suporte a UEFI para VMs.
    - cpu-checker # Verifica suporte à virtualização no processador.
    - gnome-boxes # Programa utilitário para VMs
    - gnome-software-plugin-flatpak # Integração do Flatpak ao GNOME Software.

  late-commands: # Comandos executados no final da instalação, mas ainda no ambiente de instalação.
    # Instala o Docker usando o script oficial da Docker Inc.
    - curtin in-target --target=/target -- bash -c "curl -fsSL https://get.docker.com/ | bash"

      # Instala o NodeJS LTS via nodeSource
    - curtin in-target --target=/target -- bash -c "curl -fsSL https://deb.nodesource.com/setup_lts.x | bash"

      # Adiciona o repositório do flathub
    - curtin in-target --target=/target -- sh -c "flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"

  snaps:
    - name: brave
    - name: onlyoffice-desktopeditors
    - name: insomnia
    - name: code
      classic: true
    - name: sublime-text
      classic: true
    - name: chromium

  user-data: # Configurações executadas no primeiro boot do sistema instalado.
    package_update: false # Não atualizar pacotes nesse momento.
    package_upgrade:
      false # Não atualizar o sistema nesse momento.
      # Comandos executados no primeiro boot.
    runcmd:
      - [chown, -R, vandoir:vandoir, /home/vandoir] # Garante permissões do diretório home,.
      - [usermod, -aG, docker, vandoir] # Adiciona o usuário ao grupo docker.
